name: Ubuntu Terminal

on:
  push:
    branches:
      - main
      
jobs:
  command:
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: |
          aws iam create-open-id-connect-provider \
          --url https://token.actions.githubusercontent.com \
          --client-id-list sts.amazonaws.com \
          --thumbprint-list 959CB2B52B4AD201A593847ABCA32FF48F838C2E
